version: "3.8"
services:
  pv-ai:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NO_DB_MODE=true
    volumes:
      - ./whisper-provoc-small:/app/whisper-provoc-small
