"""initial schema

Revision ID: 4a57415a185a
Revises:
Create Date: 2026-05-19 20:08:57.363509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a57415a185a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('YelpBusinesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('businessId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviewCount', sa.Integer(), nullable=True),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.Column('hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('isMock', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('businessId')
    )
    op.create_table('Lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Memos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('color', sa.Enum('yellow', 'pink', 'blue', 'green', 'purple', 'orange', name='memo_color'), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('isPinned', sa.Boolean(), nullable=True),
    sa.Column('isArchived', sa.Boolean(), nullable=True),
    sa.Column('rotation', sa.Float(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('YelpReviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('businessId', sa.String(), nullable=False),
    sa.Column('businessName', sa.String(), nullable=False),
    sa.Column('businessAddress', sa.String(), nullable=True),
    sa.Column('businessPhone', sa.String(), nullable=True),
    sa.Column('emotionalTag', sa.Enum('happy', 'sad', 'mad', 'neutral', 'excited', 'disappointed', 'confused', name='emotional_tag'), nullable=False),
    sa.Column('voiceTranscription', sa.String(), nullable=True),
    sa.Column('voiceAudioUrl', sa.String(), nullable=True),
    sa.Column('feeling', sa.Enum('Angry', 'Confused', 'Neutral', 'Happy', 'Satisfied', 'Disappointed', name='review_feeling'), nullable=True),
    sa.Column('standoutAspect', sa.Enum('Service', 'Staff', 'Price', 'Env', name='standout_aspect'), nullable=True),
    sa.Column('tone', sa.Enum('Neutral', 'Balanced and factual', 'Polite', 'Gentle and constructive', name='review_tone'), nullable=True),
    sa.Column('goal', sa.Enum('Praise', 'Celebrate great service', 'Awareness', 'Share for others to know', name='review_goal'), nullable=True),
    sa.Column('overallRating', sa.Integer(), nullable=True),
    sa.Column('serviceRating', sa.Integer(), nullable=True),
    sa.Column('environmentRating', sa.Integer(), nullable=True),
    sa.Column('priceRating', sa.Integer(), nullable=True),
    sa.Column('finalReviewText', sa.String(), nullable=True),
    sa.Column('postedOn', sa.Enum('yelp', 'draft', name='posted_site'), nullable=True),
    sa.Column('postedDate', sa.DateTime(), nullable=True),
    sa.Column('chatHistory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('draft', 'review_chat', 'enhancing', 'preview', 'posted', name='review_status'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('estimatedTime', sa.Integer(), nullable=True),
    sa.Column('actualTime', sa.Integer(), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='task_priority'), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=True),
    sa.Column('recurring', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('listId', sa.UUID(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listId'], ['Lists.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('taskId', sa.UUID(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['taskId'], ['Tasks.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('taskId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['taskId'], ['Tasks.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subtasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('sortOrder', sa.Integer(), nullable=True),
    sa.Column('taskId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['taskId'], ['Tasks.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subtasks')
    op.drop_table('Sessions')
    op.drop_table('Notes')
    op.drop_table('Tasks')
    op.drop_table('YelpReviews')
    op.drop_table('Memos')
    op.drop_table('Lists')
    op.drop_table('YelpBusinesses')
    op.drop_table('Users')
    # ### end Alembic commands ###
